### ISSUE TITLE
Won't launch -- how does installation work? Documentation doesn't explain.

### ISSUE THREAD

**Issue by kenoiyan** [francot514/Project-SimsVille#13]
System: Windows 11

Steps taken:

~~1. Downloaded the latest release, unpacked it
2. Copied all my Sims game files to the FreeSims directory
3. Ran SimsVille.exe~~

1. Installed the game and its expansion packs (House Party, Hot Date, Vacation) from the retail CDs
2. Ran SimsVille.exe

Expected outcome: The game starts.

Actual outcome:

![image](https://github.com/francot514/FreeSims/assets/168209778/cbd47307-5185-4d69-b410-ba8bca663302)

Tried installing the game to both directly the C drive, and to Program Files. Same outcome: the above error and crash.

**Comment by delipunch** [comment]
Did you install the Sims 1 to your D: drive, and are you trying to run SimsVille (with the Sims 1 files in it) from your C: drive?

If the answer to both is yes, then what I believe is happening is that the Sims 1 adds a registry key describing where it is, and you moved the files away from there. This causes SimsVille to look in a place that no longer exists for the Sims 1 install. Try moving the Sims 1 files back, or just reinstalling it.

(Also, you left your Windows username uncensored in the CMD windows contents).

**Comment by kenoiyan** [comment]
Hi, thanks for the helpful suggestions.

That is not my username -- that's what's so weird about this error log. It seems SimsVille has some paths hardcoded in it. Paths that are paths on the original developer's computer? It's looking for things that don't exist on my computer.

Also, why is SimsVille looking for the Sims installation registry key? Why on earth stick to the DRM? Isn't the whole point of a free and open source implementation of the engine to move away from dependence on a CD (and installation)? If you have the game files, the assets, that should be enough, no?

(I have legal copies of the game and its expansions, but I, like so many people these days, no longer have a CD drive in my computer. I was hoping this free and open source version of the engine would be able to run the game without the need for the CD.)

**Comment by kenoiyan** [comment]
Furthermore, I don't even have a D drive on my computer. 🤨 🤔

So why is it looking for stuff on the D drive?

Totally bonkers -- I can't make sense of the error log.

**Comment by francot514** [comment]
You should own the game and have it installed in order to get it working, copying files to directory is not needed,

**Comment by kenoiyan** [comment]
Own it, installed it (though I thought the whole point of this project is for the software _not_ to rely on the CD). Exactly the same error, same outcome.

**Comment by kenoiyan** [comment]
Is the software expecting The Sims installation in a particular, fixed location?

Edit:

I tried both `C:\\The Sims\`, and `C:\\Program Files (x86)\The Sims\`. No dice. It makes no difference. The software just crashes with the same above error.

As it currently stands, it's completely useless for the public. A broken software/build.

**Comment by kenoiyan** [comment]
Are these prerequisites for building FreeSims, or for running the build/software?

```
-Windows
MonoGame: 3.6 or higher
OpenTK 1.2

-Linux
OpenGL 3.0
SDL2
```

Again, not clear in the documentation.

Do I need to install both MonoGame and OpenTK on Windows, in addition to The Sims, to be able to run this software? Or are these frameworks and libraries included in the software build?

**Comment by francot514** [comment]
Sorry for not being clear , it needs All Expansion pack or The Sims Complete. Those are the prerequisites appart of the game.

**Comment by kenoiyan** [comment]
😠 😮‍💨

Would have helped to say that before I had to track down an external CD drive and install the game twice! Thanks a lot for your support.

Open source software without proper documentation may as well be garbage. It's useful to only one person: yourself. Then don't open source it, just keep it as your personal software.

I'll never be touching this software again, that's for sure. This was enough for a lifetime for me.

**Comment by rastilin** [comment]
> 😠 😮‍💨
> 
> Would have helped to say that before I had to track down an external CD drive and install the game twice! Thanks a lot for your support.
> 
> Open source software without proper documentation may as well be garbage. It's useful to only one person: yourself. Then don't open source it, just keep it as your personal software.
> 
> I'll never be touching this software again, that's for sure. This was enough for a lifetime for me.

This is harsh but fundamentally true. There's a certain threshold where it's so much of a hassle to get working that it might as well not exist at all.

**Comment by francot514** [comment]
Sure my mistake i have updated readme to specify how to build and run the project

**Comment by PythonTrousers** [comment]
I am having the same problem. The downloadable pre-compile has hard coded directories of the dev's computer. See below. This is not my username nor do I have visual studio installed on one drive. 

![Image](https://github.com/user-attachments/assets/aac9347f-3876-42a1-b8da-4243d7802091)

**Comment by francot514** [comment]
Are u sure using the latest precompiled version?

**Comment by alexjyong** [comment]
@francot514  I had a similar issue with the latest precompiled version, references to hard coded directories.

**Comment by francot514** [comment]
Similar about tuning.dat? or different file name=?

**Comment by alexjyong** [comment]
I was able to get around the tuning.dat error with adding a `config.ini` file in the root of the  extracted release folder with

```
[Startup]
StartupPath=<path to TS1 installation>
```

Now I have this 

![Image](https://github.com/user-attachments/assets/430f3547-85a3-4ab1-b85f-0343e4cfc9ca)

I'm half tempted at trying my hand at taking a look at it and building it to see if that helps matters with some tweaks. 

@francot514 I see you've done some commits since the last release. Are they ready to be built or should I build from the last release commit?

**Comment by alexjyong** [comment]
Oh I should also add I manually added the dll files from the repo into the release since it was complaining about missing them.

**Comment by francot514** [comment]
The latest commits from master branch can be built, i never noticed config.ini worked in main folder, it is located at Content folder

**Comment by alexjyong** [comment]
Did you ever have to do modifications to config.ini to get this to work?

**Comment by francot514** [comment]
Not really, you installed Monogame framework and openal

**Comment by alexjyong** [comment]
@francot514 sorry for the delay. I believe I did, but I'll double check when I get a chance. It's probably going to end up being something stupid.

**Comment by francot514** [comment]
Try to build yourself with visual studio and let me know the right place where you get error

**Comment by alexjyong** [comment]
<img width="1150" height="289" alt="Image" src="https://github.com/user-attachments/assets/fe949b9c-c563-44f7-b4fe-979c6a6f0bdf" />

I got this now, but I put tuning.dat in my Sims install directory (I rebuilt the game)

FWIW, I have Simitone and it works fine, which AFAIK has similar requirements.

**Comment by francot514** [comment]
Not sure how you doing this, but tuning.dat should go in Content folder. Sure it has same requeriments, because its based on it

**Comment by ThreeDeeJay** [comment]
I installed both TS1 Complete Collection and TSO but I get this error:
```
Project FreeSims Started...
SimsVille loading...

Unhandled Exception: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.MemoryStream.InternalReadInt32()
   at System.IO.BinaryReader.ReadInt32()
   at FSO.Files.Utils.IoBuffer.ReadInt32() in C:\Users\tote5\OneDrive\Documentos\Visual Studio 2017\Projects\FreeSims\sims.files\utils\IoBuffer.cs:line 128
   at FSO.Files.Formats.IFF.Chunks.NGBH.Read(IffFile iff, Stream stream) in C:\Users\tote5\OneDrive\Documentos\Visual Studio 2017\Projects\FreeSims\sims.files\formats\iff\chunks\NGBH.cs:line 48
   at FSO.Files.Formats.IFF.IffFile.prepare[T](Object input) in C:\Users\tote5\OneDrive\Documentos\Visual Studio 2017\Projects\FreeSims\sims.files\formats\iff\IffFile.cs:line 204
   at FSO.Files.Formats.IFF.IffFile.List[T]() in C:\Users\tote5\OneDrive\Documentos\Visual Studio 2017\Projects\FreeSims\sims.files\formats\iff\IffFile.cs:line 273
   at FSO.Content.TS1.TS1NeighborhoodProvider.InitSpecific(Int32 id) in C:\Users\tote5\OneDrive\Documentos\Visual Studio 2017\Projects\FreeSims\SimsVille\ContentManager\other\TS1NeighbourProvider.cs:line 63
   at FSO.Content.TS1.TS1NeighborhoodProvider..ctor(Content contentManager) in C:\Users\tote5\OneDrive\Documentos\Visual Studio 2017\Projects\FreeSims\SimsVille\ContentManager\other\TS1NeighbourProvider.cs:line 38
   at FSO.Content.Content..ctor(String basePath, GraphicsDevice device) in C:\Users\tote5\OneDrive\Documentos\Visual Studio 2017\Projects\FreeSims\SimsVille\ContentManager\Content.cs:line 76
   at FSO.Content.Content.Init(String basepath, GraphicsDevice device) in C:\Users\tote5\OneDrive\Documentos\Visual Studio 2017\Projects\FreeSims\SimsVille\ContentManager\Content.cs:line 30
   at FSO.Client.TSOGame.Initialize() in C:\Users\tote5\OneDrive\Documentos\Visual Studio 2017\Projects\FreeSims\SimsVille\Game.cs:line 92
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at FSO.Client.GameStartProxy.Start(Boolean useDX) in C:\Users\tote5\OneDrive\Documentos\Visual Studio 2017\Projects\FreeSims\SimsVille\GameStartProxy.cs:line 22
   at FSO.Client.Program.Main(String[] args) in C:\Users\tote5\OneDrive\Documentos\Visual Studio 2017\Projects\FreeSims\SimsVille\Program.cs:line 29
```

<img width="1721" height="341" alt="Image" src="https://github.com/user-attachments/assets/e58d7588-3b4e-4b00-b362-0ae564352ca2" />

**Comment by salvadorc17** [comment]
Any custom content included? European version?

**Comment by ThreeDeeJay** [comment]
Just vanilla TS1 Complete Collection, USA 4-disc version
Perhaps there should be more verbose logging after `SimsVille loading...` to see what it's really trying to do (maybe it's missing a file or looking in the wrong place or expecting a different version?) because that error is ambiguous/all over the place.

**Comment by salvadorc17** [comment]
Try to load game once and save after all neighbors are generated

**Comment by ThreeDeeJay** [comment]
The vanilla game doesn't run, so I tried Simitone which is playable, but even after that FS (even official build) still refuses to start, with the same error.

**Comment by salvadorc17** [comment]
Really? Vanilla is not working for you? What are your computer specs

**Comment by ThreeDeeJay** [comment]
If I try to run it normally, it says I need to run as admin. If I try that, it doesn't do anything at all. 
Older Windows compatibility mode doesn't help either.
Isn't the game known to not play nice with modern rigs? I got a 2080 Ti + i7 6th gen on Windows 11 23H2.

**Comment by salvadorc17** [comment]
Yes most times doesnt work in Win 11, thats why Legacy Collection was released and its one were using, or you could try a DirectX wrapper
